defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["CONSUMER_SECRET"] %>

test:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["CONSUMER_SECRET"] %>

production:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
